"""fixed follower error

Revision ID: 125922d3d60a
Revises: c9e5e11852c5
Create Date: 2021-02-13 02:09:02.027940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125922d3d60a'
down_revision = 'c9e5e11852c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dummy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dummy',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('dummy_body', sa.VARCHAR(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
