"""User table enhanced with About_Me and Last_Seen fields

Revision ID: 240047bca186
Revises: ced557412ffd
Create Date: 2021-02-11 15:55:59.491069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '240047bca186'
down_revision = 'ced557412ffd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
